#if defined _TTT_weaponitems_included
 #endinput
#endif
#define _TTT_weaponitems_included

#define KEV_ITEM_SHORT "kevlar"
#define KEV_T_ITEM_SHORT "kevlarT"
#define KEV_D_ITEM_SHORT "kevlarD"

#define HELM_ITEM_SHORT "helm"
#define HELM_T_ITEM_SHORT "helmT"
#define HELM_D_ITEM_SHORT "helmD"

#define KEVHELM_ITEM_SHORT "khelm"
#define KEVHELM_T_ITEM_SHORT "khelmT"
#define KEVHELM_D_ITEM_SHORT "kelmD"

#define HEAVY_ITEM_SHORT "heavy"
#define HEAVY_T_ITEM_SHORT "heavyT"
#define HEAVY_D_ITEM_SHORT "heavyD"

#define USP_ITEM_SHORT "usps"
#define M4_ITEM_SHORT "m4a1s"
#define AWP_ITEM_SHORT "awp"
#define KF_ITEM_SHORT "1knife"