#if defined _ttt_weapons_included
    #endinput
#endif
#define _ttt_weapons_included

#define KEV_ITEM_SHORT "kevlar"
#define KEV_T_ITEM_SHORT "kevlarT"
#define KEV_D_ITEM_SHORT "kevlarD"

#define HELM_ITEM_SHORT "helm"
#define HELM_T_ITEM_SHORT "helmT"
#define HELM_D_ITEM_SHORT "helmD"

#define KEVHELM_ITEM_SHORT "kevhelm"
#define KEVHELM_T_ITEM_SHORT "kevhelmT"
#define KEVHELM_D_ITEM_SHORT "kevhelmD"

#define HEAVY_ITEM_SHORT "heavy"
#define HEAVY_T_ITEM_SHORT "heavyT"
#define HEAVY_D_ITEM_SHORT "heavyD"

// Weapons
#define USP_ITEM_SHORT "usps"
#define MP5SD_ITEM_SHORT "mp5sd"
#define M4_ITEM_SHORT "m4a1s"
#define AWP_ITEM_SHORT "awp"
#define KF_ITEM_SHORT "1knife"
#define AK_ITEM_SHORT "ak47"
#define DEAGLE_ITEM_SHORT "deagle"
#define REVOLVER_ITEM_SHORT "revolver"
#define SCOUT_ITEM_SHORT "sg008"
#define HAMMER_ITEM_SHORT "hammer"
#define AXE_ITEM_SHORT "axe"
#define SPANNER_ITEM_SHORT "spanner"
#define BREACHCHARGE_ITEM_SHORT "breach"