name: Check files with ColorLib - Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod" >> $GITHUB_ENV
          echo "TOOLS_PATH=$GITHUB_WORKSPACE/tools" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: python3 -m pip install --upgrade pip setuptools wheel

      - name: Clone
        uses: actions/checkout@v4
        with:
          repository: 'c0rp3n/colorlib-check'
          ref: 'master'
          path: 'deps/colorlib-check'

      - name: Install
        run: |
          pip install -r ./requirements.txt
          python3 ./setup.py install
        working-directory: ./deps/colorlib-check/

      - name: Check Files
        run: |
          for file in $(find . -name '*.phrases.txt')
          do
            echo -e "Checking $file..."
            colorlib_check -r -c "$TOOLS_PATH/ttt_colors.yaml" $file
          done
        working-directory: ${{ env.SOURCEMOD_PATH }}/
